import { buildSpotDiagramOption } from "./spotDiagramChartOption";
import { createAnalysisChartComponent } from "@/features/analysis/lib/createAnalysisChartComponent";
import type { SpotDiagramData } from "@/features/analysis/types/plotData";

interface SpotDiagramChartProps {
  readonly spotDiagramData: SpotDiagramData;
  readonly wavelengthLabels: readonly string[];
  readonly autoHeight?: boolean;
}

/**
 * Renders the Spot Diagram analysis view as an Apache ECharts multi-series scatter plot. The exported component is generated by `createAnalysisChartComponent(...)`, which owns DOM measurement, responsive sizing, debounced chart updates, and ECharts instance lifecycle management.
 *
 * @remarks
 * ## Key Behaviors
 *
 * - Delegates parent measurement, debounce timing, resize handling, and chart disposal to `createAnalysisChartComponent(...)`.
 * - Uses the parent width as the chart width.
 * - Injects a sizing policy where `autoHeight` uses a square chart and the fixed-height mode clamps to `min(parentWidth, parentHeight)`.
 * - Builds chart options through `buildSpotDiagramOption(...)`.
 * - Reads the active app theme via `useTheme()` and passes a resolved light/dark chart text color into `buildSpotDiagramOption(...)`.
 * - Keeps `data-testid="spot-diagram-chart"` and `aria-label="Spot diagram plot"`.
 */
export const SpotDiagramChart = createAnalysisChartComponent<
  SpotDiagramChartProps,
  { readonly spotDiagramData: SpotDiagramData; readonly wavelengthLabels: readonly string[] }
>({
  displayName: "SpotDiagramChart",
  testId: "spot-diagram-chart",
  ariaLabel: "Spot diagram plot",
  debounceMs: 500,
  getBuilderArgs: ({ spotDiagramData, wavelengthLabels }) => ({ spotDiagramData, wavelengthLabels }),
  getChartHeight: ({ parentWidth, parentHeight, autoHeight }) =>
    autoHeight ? parentWidth : Math.max(0, Math.min(parentWidth, parentHeight)),
  buildOption: ({ spotDiagramData, wavelengthLabels }, chartWidth, chartHeight, chartTextColor) =>
    buildSpotDiagramOption(spotDiagramData, wavelengthLabels, chartWidth, chartHeight, chartTextColor),
});
