import { buildRayFanChartOption } from "./rayFanChartOption";
import { createAnalysisChartComponent } from "@/features/analysis/lib/createAnalysisChartComponent";
import { useScreenBreakpoint } from "@/shared/hooks/useScreenBreakpoint";
import type { RayFanData } from "@/features/analysis/types/plotData";

interface RayFanChartProps {
  readonly rayFanData: RayFanData;
  readonly wavelengthLabels: readonly string[];
  readonly autoHeight?: boolean;
}

/**
 * Renders the Ray Fan analysis plot with Apache ECharts using worker-provided `RayFanData`. The exported component is generated by `createAnalysisChartComponent(...)`, which mirrors `OpdFanChart` and delegates all series/layout construction to `rayFanChartOption.ts`.
 *
 * @remarks
 * ## Key Behaviors
 *
 * - Delegates parent measurement, debounce timing, resize handling, and chart disposal to `createAnalysisChartComponent(...)`.
 * - Initializes an ECharts canvas instance lazily and reuses it until unmount.
 * - Calls `useScreenBreakpoint()` through the chart factory runtime context and treats `screenSM` as the stacked small-screen fan layout.
 * - Uses an injected sizing policy where large screens keep `max(round(parentWidth / 2), 320)` and small screens use `max(round(parentWidth), 560)`; fixed-height mode clamps either policy to the parent height.
 * - Reads the active app theme via `useTheme()` and passes a resolved light/dark chart text color into `buildRayFanChartOption(...)`.
 * - Passes the small-screen flag into `buildRayFanChartOption(...)` so the pure option builder can choose side-by-side or stacked subplot geometry.
 * - Exposes `data-testid="ray-fan-chart"` and `aria-label="Ray fan plot"`.
 */
export const RayFanChart = createAnalysisChartComponent<
  RayFanChartProps,
  { readonly rayFanData: RayFanData; readonly wavelengthLabels: readonly string[]; readonly isSmallScreen: boolean },
  boolean
>({
  displayName: "RayFanChart",
  testId: "ray-fan-chart",
  ariaLabel: "Ray fan plot",
  debounceMs: 500,
  useRuntimeContext: () => useScreenBreakpoint() === "screenSM",
  getBuilderArgs: ({ rayFanData, wavelengthLabels }, isSmallScreen) => ({
    rayFanData,
    wavelengthLabels,
    isSmallScreen,
  }),
  getChartHeight: ({ parentWidth, parentHeight, autoHeight }, isSmallScreen) => {
    const widthBasedHeight = isSmallScreen
      ? Math.max(Math.round(parentWidth), 560)
      : Math.max(Math.round(parentWidth / 2), 320);

    return autoHeight
      ? widthBasedHeight
      : Math.max(0, Math.min(parentHeight, widthBasedHeight));
  },
  isDimensionValid: ({ width, height }) => width > 0 && height > 0,
  buildOption: ({ rayFanData, wavelengthLabels, isSmallScreen }, chartWidth, chartHeight, chartTextColor) =>
    buildRayFanChartOption(rayFanData, wavelengthLabels, chartWidth, chartHeight, chartTextColor, isSmallScreen),
});
