/**
Defines the type used to represent rows in the LensEditor AG Grid, covering the object plane, optical surfaces, and the image plane.

## Edge Cases / Error Handling

- `id` is always present regardless of `kind`; it is used as the AG Grid row identifier.
- Object and image rows use the stable constants `OBJECT_ROW_ID` / `IMAGE_ROW_ID`; surface rows use generated IDs from `generateRowId()` in `gridTransform.ts`.
- The `kind` discriminant should be checked before accessing kind-specific fields.

## Dependencies

- `shared/lib/types/opticalModel.ts` — `Surface`, `Surfaces` (type-only imports)
*/
import type { Surface, Surfaces } from "@/shared/lib/types/opticalModel";

export const OBJECT_ROW_ID = "row-object";
export const IMAGE_ROW_ID = "row-image";

/**
### `GridRow` discriminant

| `kind` | Extra fields | Notes |
|---|---|---|
| `"object"` | `objectDistance: number`, `medium: string`, `manufacturer: string` | Object-space gap plus editable object medium/manufacturer shown in the Medium column |
| `"image"` | `curvatureRadius`, optional `decenter` | Mirrors `Surfaces["image"]` |
| `"surface"` | All `Surface` fields | Mid-system surfaces; `id` is generated by `generateRowId()` |
*/
export type GridRow = { readonly id: string } & (
  | {
      readonly kind: "object";
      objectDistance: Surfaces["object"]["distance"];
      medium: Surfaces["object"]["medium"];
      manufacturer: Surfaces["object"]["manufacturer"];
    }
  | ({ readonly kind: "image" } & Surfaces["image"])
  | ({ readonly kind: "surface" } & Surface)
);
