/** Lens-editor grid row ids and its Object/Surface/Image discriminated union. */
import type { Surface, Surfaces } from "@/shared/lib/types/opticalModel";

/** Stable Object-plane grid row id. */
export const OBJECT_ROW_ID = "row-object";
/** Stable Image-plane grid row id. */
export const IMAGE_ROW_ID = "row-image";

/**
 * Editor row discriminated by `kind`; every variant carries an AG Grid id.
 *
 * | `kind` | Extra fields | Notes |
 * |---|---|---|
 * | `"object"` | `objectDistance: number`, `medium: string`, `manufacturer: string` | Object-space gap plus editable object medium/manufacturer shown in the Medium column |
 * | `"image"` | `curvatureRadius`, optional `decenter` | Mirrors `Surfaces["image"]` |
 * | `"surface"` | All `Surface` fields | Mid-system surfaces; `id` is generated by `generateRowId()` |
 */
export type GridRow = { readonly id: string } & (
  | {
      readonly kind: "object";
      objectDistance: Surfaces["object"]["distance"];
      medium: Surfaces["object"]["medium"];
      manufacturer: Surfaces["object"]["manufacturer"];
    }
  | ({ readonly kind: "image" } & Surfaces["image"])
  | ({ readonly kind: "surface" } & Surface)
);
