import { buildOpdFanChartOption } from "./opdFanChartOption";
import { createAnalysisChartComponent } from "@/features/analysis/lib/createAnalysisChartComponent";
import { useScreenBreakpoint } from "@/shared/hooks/useScreenBreakpoint";
import type { OpdFanData } from "@/features/analysis/types/plotData";

interface OpdFanChartProps {
  readonly opdFanData: OpdFanData;
  readonly wavelengthLabels: readonly string[];
  readonly autoHeight?: boolean;
}

/**
 * Renders the OPD Fan analysis view as an Apache ECharts canvas chart with two side-by-side subplots: Tangential and Sagittal. The exported component is generated by `createAnalysisChartComponent(...)`, which owns DOM measurement, responsive sizing, debounced chart updates, and ECharts instance lifecycle management.
 *
 * @remarks
 * ## Key Behaviors
 *
 * - Builds the chart option with `buildOpdFanChartOption(...)`.
 * - Delegates parent measurement, debounce timing, resize handling, and chart disposal to `createAnalysisChartComponent(...)`.
 * - Reads the active app theme via `useTheme()` and passes a resolved light/dark chart text color into `buildOpdFanChartOption(...)`.
 * - Calls `useScreenBreakpoint()` through the chart factory runtime context and treats `screenSM` as the stacked small-screen fan layout.
 * - Injects a sizing policy where large screens keep `max(round(parentWidth / 2), 320)` and small screens use `max(round(parentWidth), 560)`; fixed-height mode clamps either policy to the parent height.
 * - Passes the small-screen flag into `buildOpdFanChartOption(...)` so the pure option builder can choose side-by-side or stacked subplot geometry.
 * - Exposes `data-testid="opd-fan-chart"` and `aria-label="OPD fan plot"` for tests and accessibility.
 */
export const OpdFanChart = createAnalysisChartComponent<
  OpdFanChartProps,
  { readonly opdFanData: OpdFanData; readonly wavelengthLabels: readonly string[]; readonly isSmallScreen: boolean },
  boolean
>({
  displayName: "OpdFanChart",
  testId: "opd-fan-chart",
  ariaLabel: "OPD fan plot",
  debounceMs: 500,
  useRuntimeContext: () => useScreenBreakpoint() === "screenSM",
  getBuilderArgs: ({ opdFanData, wavelengthLabels }, isSmallScreen) => ({
    opdFanData,
    wavelengthLabels,
    isSmallScreen,
  }),
  getChartHeight: ({ parentWidth, parentHeight, autoHeight }, isSmallScreen) => {
    const widthBasedHeight = isSmallScreen
      ? Math.max(Math.round(parentWidth), 560)
      : Math.max(Math.round(parentWidth / 2), 320);

    return autoHeight
      ? widthBasedHeight
      : Math.max(0, Math.min(parentHeight, widthBasedHeight));
  },
  isDimensionValid: ({ width, height }) => width > 0 && height > 0,
  buildOption: ({ opdFanData, wavelengthLabels, isSmallScreen }, chartWidth, chartHeight, chartTextColor) =>
    buildOpdFanChartOption(opdFanData, wavelengthLabels, chartWidth, chartHeight, chartTextColor, isSmallScreen),
});
