/**
# `features/analysis/components/SurfaceBySurface3rdOrderChart/SurfaceBySurface3rdOrderChart.tsx`

## Data Shape

- `surfaceBySurface3rdOrderData.aberrTypes` provides the five legend/series names.
- `surfaceBySurface3rdOrderData.surfaceLabels` provides the x-axis categories.
- `surfaceBySurface3rdOrderData.data[rowIdx]` provides one bar series per Seidel aberration type.
*/
import { buildSurfaceBySurface3rdOrderChartOption } from "./surfaceBySurface3rdOrderChartOption";
import { createAnalysisChartComponent } from "@/features/analysis/lib/createAnalysisChartComponent";
import type { SeidelSurfaceBySurfaceData } from "@/features/lens-editor/types/seidelData";

/**
## Props

```ts
interface SurfaceBySurface3rdOrderChartProps {
  surfaceBySurface3rdOrderData: SeidelSurfaceBySurfaceData;
  autoHeight?: boolean;
}
```
*/
interface SurfaceBySurface3rdOrderChartProps {
  readonly surfaceBySurface3rdOrderData: SeidelSurfaceBySurfaceData;
  readonly autoHeight?: boolean;
}

/**
## Purpose

Dedicated ECharts renderer for the analysis panel’s surface-by-surface third-order Seidel aberration view. The exported component is generated by `createAnalysisChartComponent(...)`, consumes `SeidelSurfaceBySurfaceData`, and renders a grouped bar chart using the default ECharts series palette.

## Key Behaviors

- Uses `buildSurfaceBySurface3rdOrderChartOption(...)` to translate Seidel surface data into a grouped bar chart.
- Delegates parent measurement, debounce timing, resize handling, and chart disposal to `createAnalysisChartComponent(...)`.
- Reads the active app theme via `useTheme()` and passes a resolved light/dark chart text color into `buildSurfaceBySurface3rdOrderChartOption(...)`.
- Injects a sizing policy where `autoHeight` uses `max(round(parentWidth * 0.6), 320)` and fixed-height mode clamps to `min(parentHeight, max(round(parentWidth * 0.6), 320))` so tall containers cannot stretch the chart beyond the intended layout.
- Exposes `data-testid="surface-by-surface-3rd-order-chart"` for tests.
*/
export const SurfaceBySurface3rdOrderChart = createAnalysisChartComponent<
  SurfaceBySurface3rdOrderChartProps,
  SeidelSurfaceBySurfaceData
>({
  displayName: "SurfaceBySurface3rdOrderChart",
  testId: "surface-by-surface-3rd-order-chart",
  ariaLabel: "Surface by surface 3rd order aberration plot",
  debounceMs: 500,
  getBuilderArgs: ({ surfaceBySurface3rdOrderData }) => surfaceBySurface3rdOrderData,
  getChartHeight: ({ parentWidth, parentHeight, autoHeight }) =>
    autoHeight
      ? Math.max(Math.round(parentWidth * 0.6), 320)
      : Math.max(0, Math.min(parentHeight, Math.max(Math.round(parentWidth * 0.6), 320))),
  isDimensionValid: ({ width, height }) => width > 0 && height > 0,
  buildOption: (surfaceBySurface3rdOrderData, chartWidth, chartHeight, chartTextColor) =>
    buildSurfaceBySurface3rdOrderChartOption(surfaceBySurface3rdOrderData, chartWidth, chartHeight, chartTextColor),
});
